namespace ScoutVoiceEngine;

internal sealed record LanguageResources(
    string ModelLanguage,
    string TtsCulture,
    RuntimeMessages Runtime,
    string Title,
    string Heading,
    string Intro,
    string Loading,
    string Record,
    string Privacy,
    string Listening,
    string Wait,
    string NotRecognized,
    string NoResult,
    string VoiceMismatch,
    string Recognized,
    string Complete,
    string Ready,
    string Threshold,
    string Finish,
    string Retry,
    string InitFailed,
    string Prompt,
    string CancelTitle,
    string Cancel,
    string[] Phrases)
{
    public static IReadOnlyDictionary<string, LanguageResources> All { get; } =
        new Dictionary<string, LanguageResources>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new(
                "en", "en-US", new(
                    "Preparing the voice engine", "Waiting for “Hey Scout”",
                    "Please say a command", "Processing", "Speaking",
                    "I couldn't verify the registered voice.", "Command canceled.",
                    "I couldn't process the command. Please check the log.",
                    "Waiting for execution confirmation",
                    "This command requires confirmation. {0}. To execute it, say “confirm and execute.”",
                    "I didn't hear a command."),
                "Scout Voice Setup", "Register my voice",
                "Record five different sentences to create your voice profile. Read them naturally in a quiet place.",
                "Preparing the voice model...", "Record sentence",
                "Original recordings are not saved. Only speaker characteristics calculated from the five recordings are encrypted for your Windows account and stored.",
                "{0}/5 · Listening now without a chime", "Read the sentence, then remain quiet for a moment.",
                "The sentence was not recognized clearly: “{0}”", "no recognition result",
                "This voice differs too much from the earlier recordings. Please have the same person try again.",
                "Recognized: {0}", "Voice registration is complete.",
                "You can now say “Hey Scout” to activate voice control.",
                "Speaker verification threshold: {0:F2}", "Done", "Record again",
                "Initialization failed", "{0}/5 · Read the sentence below",
                "Cancel setup", "Stop voice registration?",
                [
                    "Hey Scout, tell me today's schedule.",
                    "Hey Scout, check my important emails.",
                    "Hey Scout, tell me the weather in Seoul.",
                    "Hey Scout, set a reminder for tomorrow morning.",
                    "Hey Scout, respond only to my voice from now on.",
                ]),
            ["ko"] = new(
                "ko", "ko-KR", new(
                    "음성 엔진을 준비하는 중", "“헤이 스카웃”을 기다리는 중",
                    "명령을 말씀하세요", "처리 중", "말하는 중",
                    "등록된 음성을 확인하지 못했습니다.", "명령을 취소했습니다.",
                    "명령을 처리하지 못했습니다. 로그를 확인해 주세요.",
                    "실행 확인 대기 중",
                    "확인이 필요한 명령입니다. {0}. 실행하려면 확인하고 실행해라고 말해 주세요.",
                    "명령을 듣지 못했습니다."),
                "Scout 음성 설정", "내 목소리 등록",
                "서로 다른 5개 문장을 듣고 음성 특징을 등록합니다. 조용한 곳에서 평소 말투로 읽어 주세요.",
                "음성 모델을 준비하고 있습니다...", "문장 녹음",
                "음성 원본은 저장하지 않습니다. 5개 녹음에서 계산한 화자 특징만 Windows 사용자 계정으로 암호화해 저장합니다.",
                "{0}/5 · 신호음 없이 바로 듣고 있습니다", "문장을 읽은 뒤 잠시 조용히 기다려 주세요.",
                "문장을 충분히 인식하지 못했습니다: “{0}”", "인식 결과 없음",
                "앞서 등록한 목소리와 차이가 큽니다. 같은 사람이 다시 읽어 주세요.",
                "인식 결과: {0}", "목소리 등록이 완료되었습니다.",
                "이제 “헤이 스카웃”이라고 부르면 응답합니다.",
                "화자 구분 기준값: {0:F2}", "완료", "다시 녹음",
                "초기화 실패", "{0}/5 · 아래 문장을 읽어 주세요",
                "설정 취소", "목소리 등록을 중단할까요?",
                [
                    "헤이 스카웃, 오늘의 일정을 알려줘.",
                    "헤이 스카웃, 중요한 이메일을 확인해 줘.",
                    "헤이 스카웃, 서울의 날씨를 알려줘.",
                    "헤이 스카웃, 내일 아침 알림을 설정해 줘.",
                    "헤이 스카웃, 지금부터 내 목소리에만 응답해.",
                ]),
            ["ja"] = new(
                "ja", "ja-JP", new(
                    "音声エンジンを準備しています", "「Hey Scout」を待っています",
                    "コマンドを話してください", "処理中", "読み上げ中",
                    "登録された声を確認できませんでした。", "コマンドをキャンセルしました。",
                    "コマンドを処理できませんでした。ログを確認してください。",
                    "実行の確認を待っています",
                    "確認が必要なコマンドです。{0}。実行するには「確認して実行」と言ってください。",
                    "コマンドを聞き取れませんでした。"),
                "Scout 音声設定", "自分の声を登録",
                "5つの異なる文を録音して音声プロファイルを作成します。静かな場所で自然に読んでください。",
                "音声モデルを準備しています...", "文を録音",
                "元の録音は保存されません。5つの録音から計算した話者特徴のみをWindowsアカウント用に暗号化して保存します。",
                "{0}/5 · 合図音なしで録音中", "文を読んだ後、しばらく静かにしてください。",
                "文を十分に認識できませんでした: 「{0}」", "認識結果なし",
                "前の録音と声が大きく異なります。同じ人がもう一度読んでください。",
                "認識結果: {0}", "音声登録が完了しました。",
                "「Hey Scout」と呼びかけると応答します。",
                "話者確認のしきい値: {0:F2}", "完了", "もう一度録音",
                "初期化に失敗しました", "{0}/5 · 以下の文を読んでください",
                "設定をキャンセル", "音声登録を中止しますか？",
                [
                    "ヘイ スカウト、今日の予定を教えて。",
                    "ヘイ スカウト、重要なメールを確認して。",
                    "ヘイ スカウト、ソウルの天気を教えて。",
                    "ヘイ スカウト、明日の朝にリマインダーを設定して。",
                    "ヘイ スカウト、これから私の声だけに応答して。",
                ]),
            ["zh-Hans"] = new(
                "zh", "zh-CN", new(
                    "正在准备语音引擎", "正在等待“Hey Scout”",
                    "请说出命令", "正在处理", "正在朗读",
                    "无法验证已注册的声音。", "命令已取消。",
                    "无法处理命令，请检查日志。",
                    "正在等待执行确认",
                    "此命令需要确认：{0}。如需执行，请说“确认并执行”。",
                    "未听清命令。"),
                "Scout 语音设置", "注册我的声音",
                "录制五个不同的句子以创建语音配置。请在安静的地方自然朗读。",
                "正在准备语音模型...", "录制句子",
                "不会保存原始录音。仅保存由五次录音计算出的说话人特征，并使用当前Windows账户进行加密。",
                "{0}/5 · 正在录音，不播放提示音", "读完句子后请保持片刻安静。",
                "未能清楚识别句子：“{0}”", "无识别结果",
                "声音与之前的录音差异过大。请由同一个人重新朗读。",
                "识别结果：{0}", "语音注册已完成。",
                "现在说“Hey Scout”即可唤醒语音控制。",
                "说话人验证阈值：{0:F2}", "完成", "重新录制",
                "初始化失败", "{0}/5 · 请朗读下面的句子",
                "取消设置", "停止语音注册吗？",
                [
                    "嘿 Scout，告诉我今天的日程。",
                    "嘿 Scout，查看我的重要邮件。",
                    "嘿 Scout，告诉我首尔的天气。",
                    "嘿 Scout，设置明天早上的提醒。",
                    "嘿 Scout，从现在开始只响应我的声音。",
                ]),
        };
}

internal sealed record RuntimeMessages(
    string Starting,
    string Waiting,
    string SpeakCommand,
    string Processing,
    string Speaking,
    string UnverifiedSpeaker,
    string Canceled,
    string Failed,
    string ConfirmationWaiting,
    string ConfirmationPrompt,
    string NoCommand);
